name = "StreamSampling"
uuid = "ff63dad9-3335-55d8-95ec-f8139d39e468"
version = "0.3.3"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1.8"
Accessors = "0.1"
DataStructures = "0.18"
Distributions = "0.25"
PrecompileTools = "1"
Random = "1"
StatsBase = "0.32, 0.33, 0.34"
